### ISSUE TITLE
Historia de Usuario #1 (Home)

### ISSUE THREAD

**Issue by SandraLore18** [PQ2505/DEV002-social-network#6]

**Comment by PQ2505** [comment]
Historia de Usuario 1 (Home)

Cómo: Usuaria nueva.
Deseo poder: Ver la página de Bienvenida del sitio Web con sus respectivos botones.
Para: Familiarizarme con el contenido inicial del sitio.

Criterios de Aceptación:

Ver el logo del Sitio Web.
Que se vea el slogan del sitio Web.
Que el botón CLICK HERE me permita dirigirme al formulario de login.
Que sea un sitio Responsive.
Manejo de GitHub en equipo.

**Comment by SandraLore18** [comment]
Se le había colocado ese nombre por que en una OH luna se lo dijo a Erika.
